services:
  postgres:
    container_name: clean-nest-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clean-nest
      PGDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres
